2021-12-30 23:53:39,726 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2021-12-30 23:55:07,292 ERROR: Exception on /edit_profile [POST] [in d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\routes.py", line 89, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3363, in flush
    self._flush(objects)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3463, in _flush
    flush_context.execute()
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 633, in execute
    uow,
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 241, in save_obj
    update,
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1001, in _emit_update_statements
    statement, multiparams, execution_options=execution_options
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "d:\knowledgegraph\pythonproject\newgraduationproject\flask_demo\venv\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('xixia123', '', 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2021-12-30 23:58:01,857 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2021-12-31 00:37:15,002 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2021-12-31 00:37:43,107 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2021-12-31 00:48:36,434 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2021-12-31 00:51:51,676 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2022-01-06 14:18:06,488 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2022-01-06 14:25:10,565 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2022-01-06 14:30:17,889 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2022-01-06 14:30:57,064 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
2022-01-06 14:31:40,355 INFO: Microblog startup [in D:\KnowledgeGraph\PythonProject\NewGraduationProject\flask_demo\app\__init__.py:44]
